# Generated by Django 2.1.5 on 2019-04-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_remove_organisations_orgid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgid', models.CharField(max_length=3)),
                ('custname', models.CharField(max_length=50)),
                ('custemail', models.CharField(max_length=100)),
                ('custphn', models.CharField(max_length=13)),
                ('custstatus', models.CharField(max_length=10)),
            ],
        ),
    ]
