# Generated by Django 2.0.5 on 2019-04-25 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_customer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
        migrations.AlterModelTable(
            name='organisations',
            table='organisations',
        ),
    ]
