# Generated by Django 2.0.5 on 2019-04-28 07:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0006_outstanding'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisations',
            name='orglogo',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
