# Generated by Django 2.1.7 on 2019-04-29 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0007_organisations_orglogo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisations',
            old_name='orgsendername',
            new_name='orgsendermail',
        ),
    ]
