# Generated by Django 2.1.7 on 2019-05-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0008_auto_20190429_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='outstanding',
            name='creditperiod',
            field=models.CharField(default=23, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='outstanding',
            name='custid',
            field=models.CharField(max_length=50),
        ),
    ]
